spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finalproject_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create