spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/finalproject_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: